### ISSUE TITLE
[doc] 0.4 README

### ISSUE THREAD

**Issue by mfazekas** [airbrake/airbrake-js#137]
Some suggestions for improvements:
* is this current version stable? if not you might want to link to the latest stable
* compared to v0.3.12 README it's not obvious how to set project key and id in new readme.
* it would be nice to have some pointers for integrating to rails apps. There are many options with npm with rails. Also there are many options for passing project id, key and env from rails to js. In both cases for getting started it would help to show your way.

**Comment by vmihailenco** [comment]
Hi,

Did you check examples at https://github.com/airbrake/airbrake-js/tree/master/examples ? They show how to setup and use notifier.

**Comment by LorenzoS92** [comment]
Really, i can't understand the current docs, even executing locally, seems that the browser can't find requireJS in first case, and in legacy case, can't find airbrake.
Even all airbrake-shim files aren't present in this repository, i can't find and i didn't understand why.

**Comment by vmihailenco** [comment]
Did you check https://github.com/airbrake/airbrake-js/tree/master/examples?

**Comment by droppedoncaprica** [comment]
The issue here is that what's in the examples directory vary wildly from how it is explained when you create a new project.  From your website:

```
 * Airbrake JavaScript notifier consists of 2 parts:
    1) Notifier shim that collects exceptions until notifier is loaded. You are supposed to host it with your JavaScript files and modify as needed, e.g. add integration with framework of your choice. See our Example for more detail.
    2) Notifier itself loaded from our CDN.
```

Your examples don't fully show what's going on other than `npm install airbrake-js` and include client and instrumentation files directly.  

No CDN example, no shim file anywhere, and the code on your actual website looks plain wrong.  The shim file loaded has the project ID, key, and environment set in the attributes rather than have to be manually initialized with JavaScript.  

`<script src="airbrake-shim.js" data-airbrake-project-id="YOUR_AIRBRAKE_ID" data-airbrake-project-key="YOUR_AIRBRAKE_KEY" data-airbrake-environment-name="ENV"></script>`

All in all the README needs a better on-boarding for how to use it.  Obviously people have read the examples, the question is that enough considering the fact that the Airbrake website itself is crazy different than said examples.

**Comment by LorenzoS92** [comment]
Thank you for the detailed explaination of what i mean for so bad documentation @droppedoncaprica
I had the chance to test other error tracking software and unfortunately this is the worse documentation comparing others.

**Comment by LorenzoS92** [comment]
Moreover during the "npm install airbrake-js" the installer shows an alpha versione of airbrake.
Are airbrake developers pushing alpha version into a stable branch?

**Comment by vmihailenco** [comment]
@droppedoncaprica, this issue is about README in the repository. That is a shame that Airbrake.io has outdated instructions, but that is a different story.

>Yes, an alpha version released to the public!

Yes, and I don't see anything wrong with it. I could name it beta or even release it as v10.0. What does it change?

> and include client and instrumentation files directly.

There is also example how to use notifier with RequireJS. If you get an error then you forgot to install requirejs via `npm install`. Yes, I could write a doc that you have to install RequireJS and that would be helpful (and I will do it). But I can also assume that you already know how to use RequireJS. Because if you don't know it is easier to load client and instrumentation directly.

---

Overall, thanks for the critic. Writing docs and especially good docs is a hard task which requires time and special skills. ProbabIy I don't have such skills, but I will do what I can.

**Comment by LorenzoS92** [comment]
Yes , it really matters because naming a plugin in *alpha* means that it's not ready for the public or it may contain some potentially bugs / code not finished.
And for an error reporting plugin is not so suggested.
It the plugin is stable and it won't contains unfinished code, please rename it to stable or avoid to put *alpha* to the name.
