### ISSUE TITLE
airbrakeJs is not defined

### ISSUE THREAD

**Issue by arol** [airbrake/airbrake-js#184]
The change on this [commit](https://github.com/airbrake/airbrake-js/commit/86f9825d527ea107f3d4a853a9d5a8645628986e#diff-0a08a7565aba4405282251491979bb6bR9) (line #9) crashes my app.

The file `lib/client.js` does not exist. I reverted it manually and it works so I would create a PR with that, but I saw there's is a commit only for this change.

How can we solve it?

**Comment by burib** [comment]
@arol as a general rule, I suggest to never rely on latest versions of any library. If you have the chance ( you should be ), fix your version number of airbrakeJs dependency to 0.5.6. 

The current ( latest ) release v0.5.7 contains the bug you've described.

Once they merge the fix for this, you can upgrade to 0.5.8 and your problem is solved.

**Comment by arol** [comment]
Ok thank you @burib! It's not in production, it occurred me in development env and I was only wondering why this change was made.

**Comment by burib** [comment]
@arol the story behind why was it changed is here -> https://github.com/airbrake/airbrake-js/issues/179

**Comment by vmihailenco** [comment]
Should be fixed by https://github.com/airbrake/airbrake-js/pull/181
