### ISSUE TITLE
incorrect response code in the compat reporter

### ISSUE THREAD

**Issue by stevecrozz** [airbrake/airbrake-js#189]
According to these docs: https://airbrake.io/docs/#create-notice-v3
The correct response code for a new error notification is 201, but the compat reporter appears to be expecting response code 200:
https://github.com/airbrake/airbrake-js/blob/v0.5.8/src/reporters/compat.coffee#L12

Is there a reason for this? or does airbrake-js require a change here?

**Comment by felixbuenemann** [comment]
I think the question here is why is the default for no jsonp, the "compat" reporter (which expects 200) and not the "xhr" reporter (which expects 201, as documented).

**Comment by vmihailenco** [comment]
Compatible API returns 200 OK status code on success. https://airbrake.io/docs/#create-notice-v3 describes different API. That said:
- POST /api/v3/projects/:project_id/create-notice 200 OK - compatible API that benefits from https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Simple_requests
- GET /api/v3/projects/:project_id/create-notice?body=error&callback=cb 200 OK - jsonp API used when XmlHTTPRequest is not available
- POST /api/v3/projects/:project_id/notices - described in https://airbrake.io/docs/#create-notice-v3, but requires preflight request because of https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Simple_requests

>I think the question here is why is the default for no jsonp, the "compat" reporter (which expects 200) and not the "xhr" reporter (which expects 201, as documented).

Because compat API does not require custom Content-Type header which enables https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Simple_requests
