### ISSUE TITLE
Publish typescript definitions

### ISSUE THREAD

**Issue by spadgos** [airbrake/airbrake-js#348]
The library is written in typescript, but clients using this library can't use the definitions (`.d.ts` files) since they're not published. What about publishing them?

**Comment by andykellr** [comment]
It should be as simple as adding the following, but I'm having trouble building.

`tsconfig.json`:
```
  "declaration": true
```

`package.json`:
```
  "typings": "dist/client.d.ts"
```

**Comment by jonnyarnold** [comment]
I had a crack at this, but couldn't get it working. Hopefully my notes will be useful to someone!

- I tried @andykellr's suggestion, but `tsc` still couldn't find the types. I think it's probably confounded by the fact that this module exports an object, rather than a module. 
- I had a go at adding the [dts-webpack-bundler](https://github.com/eliraz-refael/dts-webpack-bundler) plugin to the Webpack configuration, but:
  - it appears to be set up for each module, rather than just the top-level module, and
  - it doesn't seem very happy with nested folders.

To get by, I've written a `.d.ts` file by hand:

```typescript
// Hand-written definition of airbrake-js 0.9.8. See issue:
// https://github.com/airbrake/airbrake-js/issues/348
declare module "airbrake-js" {
  class Client {
    constructor(opts?: any);
    public setProject(id: number, key: string): void;
    public setHost(host: string): void;
    public addReporter(name: string | Reporter): void;
    public addFilter(filter: Filter): void;
    public notify(err: any): Promise<any>;
    public wrap(fn: any): FuncWrapper;
    public call(fn: any, ...args: any[]): any;
    public onerror(): void;
  }

  interface FuncWrapper {
    (): any;
    inner: () => any;
    _airbrake?: boolean;
  }

  type Filter = (notice: Notice) => Notice | null;

  interface Notice {
    id: string;
    errors: AirbrakeError[];
    context: any;
    params: any;
    session: any;
    environment: any;
    _json?: string;
  }

  interface AirbrakeFrame {
    function: string;
    file: string;
    line: number;
    column: number;
  }

  interface AirbrakeError {
    type: string;
    message: string;
    backtrace: AirbrakeFrame[];
  }

  interface ReporterOptions {
    projectId: number;
    projectKey: string;
    host: string;
    timeout: number;
    ignoreWindowError?: boolean;
  }

  type Reporter = (
    notice: Notice,
    opts: ReporterOptions,
    promise: Promise<any>
  ) => void;

  export = Client;
}
```

This will go out of date quickly; hopefully the Airbrake authors can get the right Webpack configuration up and running!

**Comment by andykellr** [comment]
Is there any update on this? It seems strange to have the airbrake team embrace typescript enough to write their library in typescript, but to not bother to provide declarations for the library. It would make consuming this library much easier. I've been waiting to migrate our team from `airbrake` to `airbrake-js` until this is done.

**Comment by vmihailenco** [comment]
For those who are interested please take a look at https://github.com/airbrake/airbrake-js/pull/422. I've used type definitions written by @jonnyarnold with some edits - thank you.

**Comment by mwilniewiec** [comment]
I was fighting with this issue for a while and I found out that there is non-standard way of importing this in typescript:

`import Airbrake = require("airbrake-js");`
