### ISSUE TITLE
Update Changelog

### ISSUE THREAD

**Issue by hotzenklotz** [airbrake/airbrake-js#353]
Please update your change log or attach information to your releases. It is really hard to update to the lastest version without knowing about any changes. Thank you.

**Comment by vmihailenco** [comment]
We provide changelog for releases that break backwards compatibility. Please check commits if you are interested in code changes.

**Comment by jeremywadsack** [comment]
You haven't updated the changelog since v0.5.8. At that time you were adding updates with each release.

You are now at 1.0.7, which I would expect to be a breaking release if this were semantically versioned. However, I see that you have just been incrementing the number and happened to get from 0.9.9 to 1.0.0. 

You've released 49 releases over the past two years and not one of them introduced a breaking change? Even with `rc` releases?
