### ISSUE TITLE
Key security vulnerability

### ISSUE THREAD

**Issue by 1y8ws7** [airbrake/airbrake-js#4]
Currently the API key is set via function call on a page:  window.Airbrake.setKey('703c5fce534...');
The issue is: the key is publicly available and can be used for evil >:-E by any page visitor. 

Is this something that should be regarded as critical?

**Comment by choopage** [comment]
Hi @benarent 
Referring to your comment on 26 Nov 2013, 

> "I think it's less of an issue as it's just a write only key, and if someone steals it and sends bad data the key can be easily revoked."

In your mentioned solution, what if there is a group of persistent hackers targeting the site, so how many times does one have to repeat the process of revocation and re-deploy the site with the new API key?

Isn't there a way like how Firebase [firebase.google.com ](firebase.google.com) does it?
They allow users to expose their API key in client-side javascript because they have a good security rules that check for privileges before one could read or write to database, storage, and etc. 


@kyrylo #209

**Comment by zefer** [comment]
@choopage the worst case scenario here is that a malicious party could send errors or deploys to your project. It's a write-only key. This would easily be resolved by rotating your api-key, and we've not yet had any reported case of this happening.

> what if there is a group of persistent hackers targeting the site, so how many times does one have to repeat the process of revocation and re-deploy the site with the new API key?

This would be inconvenient, but it is the worst that a group of persistent hackers can achieve with your key.

**Comment by derosm2** [comment]
Any chance this could be added to the readme or a FAQ section? I think it would be good to acknowledge this upfront so people are aware of any risks, however minimal.

**Comment by vmihailenco** [comment]
Reopening this, but I think we should provide some way to improve security rather than adding a warning without possible workarounds.
