### ISSUE TITLE
where is `dist/instrumentation/jquery` ? and how to fix it?

### ISSUE THREAD

**Issue by geminiyellow** [airbrake/airbrake-js#431]
update from  1.1.0 to  1.1.1, crash.
the `jquery` has been deleted from the instrumentation.
please tell me how to fix it.
and i cannot found anything in CHANGELOG.
please write it when you guys do new release.

**Comment by vmihailenco** [comment]
It looks like jquery instrumentation was removed > year ago in https://github.com/airbrake/airbrake-js/commit/c07a10a421583414ef6875d4caaf114890a1560c. But compiled file was not removed from the dist folder so you could still reference it.

I think the fix is to not use jquery instrumentation since `window.onerror` should be enough.
