### ISSUE TITLE
sourceMapErrors: unsupported protocol scheme "chrome-extension"

### ISSUE THREAD

**Issue by zkrige** [airbrake/airbrake-js#989]
# 🐞 bug report

### Affected Package

The issue is caused by package @airbrake/node

### Is this a regression?

Not sure

### Description

 A clear and concise description of the problem...
"sourceMapErrors": {
    "chrome-extension://mgfnoholgmbdfaianbopacjnmadhekna/vendor/ember/ember.js": "Get \"chrome-extension://mgfnoholgmbdfaianbopacjnmadhekna/vendor/ember/mgfnoholgmbdfaianbopacjnmadhekna/vendor/ember/ember.map\": unsupported protocol scheme \"chrome-extension\""
  }

## 🌍  Your Environment

**@airbrake/\* version:**
<pre><code>
"@airbrake/node": "1.4.2",</code></pre>

**Anything else relevant?**
We're using NWJS (http://nwjs.io)

**Comment by thompiler** [comment]
Hi @zkrige,

Are you using our [private source maps feature](https://airbrake.io/docs/features/private-sourcemaps/)? If not, how are you specifying the source map to the minified JS?

Some other options:
- [Standard, publicly accessible source maps](https://airbrake.io/docs/features/public-sourcemaps/) (probably not since it sounds like you're tracking a Chrome extension which does not have public JS code)
- [Custom source map URLs](https://airbrake.io/docs/features/custom-sourcemap-urls/) to publicly available source maps (would be possible with a Chrome extension)

**Comment by zkrige** [comment]
thank you so much for the quick response
We're using custom source maps and uploading our our source maps 

```
curl -v https://airbrake.io/api/v4/projects/xxxx/sourcemaps -X POST -H 'Authorization: Bearer xxxx' -F file=@./build/output/result/assets/app.js.map -F name='chrome-extension://mgfnoholgmbdfaianbopacjnmadhekna/assets/app.js' -F pattern='%/app.js'
```

**Comment by thompiler** [comment]
I'm not sure you need to use custom source maps here. At least, you should try to use the standard, private source map pattern matching first since it's simpler. 

#### Here's how it works

If you have a minified file like `chrome-extension://mgfnoholgmbdfaianbopacjnmadhekna/vendor/ember/ember.js` in your Airbrake error backtrace, then Airbrake will look in your uploaded, private source maps for anything matching that file name. eg: if a source map had a pattern match of `%/ember.js`

Did you upload the source map you want to use with a pattern that matches this `ember.js` file like this?

Useful links:
- Uploading source maps and the supported attributes: https://airbrake.io/docs/features/private-sourcemaps/#upload-your-sourcemap
- Viewing your uploaded source maps: https://airbrake.io/docs/features/private-sourcemaps/#viewing-your-uploaded-sourcemaps

**Comment by zkrige** [comment]
hmm... so the problem is that it shouldn't be showing that ember.js error - that's only part of the call stack. I need to see where the error originated from in our code.

**Comment by zkrige** [comment]
I've added stack trace to context.log and im getting this
```
"log": [
    "ERROR:2021-04-06T14:08:27.990Z:\tUncaught error,chrome-extension://mgfnoholgmbdfaianbopacjnmadhekna/assets/app.js,6988,13,error\r\n"
  ],
```

but airbrake is showing me 
```
"sourceMapErrors": {
    "/Users/zayinkrige/Dropbox/Business/Snapplify/desktop viewer/build/output/result/node_modules/@airbrake/browser/dist/notifier.js": "got \"/Users/zayinkrige/Dropbox/Business/Snapplify/desktop viewer/build/output/result/node_modules/@airbrake/browser/dist/notifier.js\", expected an absolute URL",
    "chrome-extension://mgfnoholgmbdfaianbopacjnmadhekna/assets/libs/snapplify/errorHandler.js": "Get \"chrome-extension://mgfnoholgmbdfaianbopacjnmadhekna/assets/libs/snapplify/mgfnoholgmbdfaianbopacjnmadhekna/assets/libs/snapplify/errorHandler.map\": unsupported protocol scheme \"chrome-extension\""
  },
```

we're using a custom error handler:

```
window.onerror = function(message, source, lineno, colno, error) {
            console.error(error)
            const didHandle = handleError('error', message, source, lineno, colno, error)
            if (didHandle) {
                airbrake.notify({error: error, context: {log: self.logMessages}}).then(function () {
                    self.writeToFile('stack', error.stack)
                })
            }
            return true
        };
```

self.logMessages is an array of all console messages

**Comment by zkrige** [comment]
Thank you very much for the detailed response.

here is my upload script

```
#!/bin/sh
curl -v https://airbrake.io/api/v4/projects/xxx/sourcemaps -X POST -H 'Authorization: Bearer xxxx' -F file=@./build/output/result/assets/app.js.map -F name='chrome-extension://mgfnoholgmbdfaianbopacjnmadhekna/assets/app.js' -F pattern='%/app.js'
```

its possible my pattern is wrong - let me try with the pattern you have suggested

**Comment by thompiler** [comment]
>its possible my pattern is wrong - let me try with the pattern you have suggested

Sounds good! Let us know if you have any issues after updating the pattern.

The sourceMapErrors should not necessarily be an issue. They are just indicating that Airbrake doesn't think `chrome-extension://.../ember.js` is a public URL. After Airbrake checks for a source map at a public URL, it will look for a privately uploaded source map to use. As long as your errors' backtraces look unminified, then there should not be any issues.

Perhaps we could improve that error message so it's clearer. I'll let the team know.

**Comment by kyrylo** [comment]
I believe @thompiler was correct when he said that the pattern is wrong. The `ember.js` part is not matched by the pattern you provided. Please ping me if you still experience this issue or need further assistance.
